name: SuspiciousPlayers
version: ${project.version}
description: ${project.description}
api-version: 1.13
author: Karl Essinger (KarlofDuty)
website: http://karlofduty.com
load: STARTUP
main: com.karlofduty.SuspiciousPlayers.SuspiciousPlayers
permissions:
  susp.notify:
    description: Player gets notifications from the plugin.
    default: op
  susp.add:
    description: Player can add others to the suspicious players list.
    default: op
  susp.remove:
    description: Player can remove others from the suspicious players list.
    default: op
  susp.archive:
    description: Player can archive listings in the suspicious players list.
    default: op
  susp.unarchive:
    description: Player can unarchive listings in the suspicious players list.
    default: op
  susp.list:
    description: Player can add others to the suspicious players list.
    default: op
  susp.delete:
    description: Player can add delete entries from the suspicious players list.
    default: op
  susp.reload:
    description: Player can reload the plugin.
    default: op
commands:
  suspadd:
    description: Adds an entry that a player is suspicious
    usage: /suspadd <username> <description>
    permission: susp.add
  susplist:
    description: Lists all entries on a specific player.
    usage: /susplist <username>
    permission: susp.list
  susparchive:
    description: Archives an entry from a user's susplist. This command should not be used directly, it is called from the list menu.
    usage: /susparchive <id>
    permission: susp.archive
  suspunarchive:
    description: Unarchives an entry from a user's archived susplist. This command should not be used directly, it is called from the list menu.
    usage: /suspunarchive <id>
    permission: susp.unarchive
  suspdelete:
    description: Deletes an entry from a user's archived susplist. This command should not be used directly, it is called from the list menu.
    usage: /suspdelete <id>
    permission: susp.delete
  suspreload:
    description: Reloads the plugin.
    usage: /suspreload
    permission: susp.reload