database:
  # The database type, which specifies which JDBC class to use.
  # Available values: MySQL, MariaDB (case-insensitive)
  type: MariaDB
  # The address the database server runs on
  hostname: localhost
  # The port the database server listens to
  port: 3306
  # The name of the database for the plugin to use
  name: SuspiciousPlayers
  # User to log in as
  user: SuspUser
  # Password used to log in
  password: hello1234
